// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['bridge']['App']['AbsolutePath'](arg1);
}

export function CheckPermissions(arg1) {
  return window['go']['bridge']['App']['CheckPermissions'](arg1);
}

export function Copyfile(arg1, arg2) {
  return window['go']['bridge']['App']['Copyfile'](arg1, arg2);
}

export function CreateSchTask(arg1, arg2) {
  return window['go']['bridge']['App']['CreateSchTask'](arg1, arg2);
}

export function DeleteSchTask(arg1) {
  return window['go']['bridge']['App']['DeleteSchTask'](arg1);
}

export function Download(arg1, arg2) {
  return window['go']['bridge']['App']['Download'](arg1, arg2);
}

export function Exec(arg1, arg2) {
  return window['go']['bridge']['App']['Exec'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['bridge']['App']['FileExists'](arg1);
}

export function GetEnv() {
  return window['go']['bridge']['App']['GetEnv']();
}

export function GetInterfaces() {
  return window['go']['bridge']['App']['GetInterfaces']();
}

export function GetSystemProxy() {
  return window['go']['bridge']['App']['GetSystemProxy']();
}

export function HttpGet(arg1, arg2) {
  return window['go']['bridge']['App']['HttpGet'](arg1, arg2);
}

export function KillProcess(arg1) {
  return window['go']['bridge']['App']['KillProcess'](arg1);
}

export function Makedir(arg1) {
  return window['go']['bridge']['App']['Makedir'](arg1);
}

export function Movefile(arg1, arg2) {
  return window['go']['bridge']['App']['Movefile'](arg1, arg2);
}

export function ProcessInfo(arg1) {
  return window['go']['bridge']['App']['ProcessInfo'](arg1);
}

export function QuerySchTask(arg1) {
  return window['go']['bridge']['App']['QuerySchTask'](arg1);
}

export function Readfile(arg1) {
  return window['go']['bridge']['App']['Readfile'](arg1);
}

export function Removefile(arg1) {
  return window['go']['bridge']['App']['Removefile'](arg1);
}

export function RestartApp() {
  return window['go']['bridge']['App']['RestartApp']();
}

export function SetSystemProxy(arg1, arg2) {
  return window['go']['bridge']['App']['SetSystemProxy'](arg1, arg2);
}

export function StartKernel(arg1, arg2) {
  return window['go']['bridge']['App']['StartKernel'](arg1, arg2);
}

export function SwitchPermissions(arg1, arg2) {
  return window['go']['bridge']['App']['SwitchPermissions'](arg1, arg2);
}

export function UnzipZIPFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipZIPFile'](arg1, arg2);
}

export function Writefile(arg1, arg2) {
  return window['go']['bridge']['App']['Writefile'](arg1, arg2);
}
