// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function AbsolutePath(arg1:string):Promise<bridge.FlagResult>;

export function AddScheduledTask(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function CloseMMDB(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Copyfile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Download(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function Exec(arg1:string,arg2:Array<string>,arg3:bridge.ExecOptions):Promise<bridge.FlagResult>;

export function ExecBackground(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:bridge.ExecOptions):Promise<bridge.FlagResult>;

export function ExitApp():Promise<void>;

export function FileExists(arg1:string):Promise<bridge.FlagResult>;

export function GetEnv():Promise<bridge.EnvResult>;

export function GetInterfaces():Promise<bridge.FlagResult>;

export function IsStartup():Promise<boolean>;

export function KillProcess(arg1:number,arg2:number):Promise<bridge.FlagResult>;

export function ListServer():Promise<bridge.FlagResult>;

export function Makedir(arg1:string):Promise<bridge.FlagResult>;

export function Movefile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Notify(arg1:string,arg2:string,arg3:string,arg4:bridge.NotifyOptions):Promise<bridge.FlagResult>;

export function OpenMMDB(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function ProcessInfo(arg1:number):Promise<bridge.FlagResult>;

export function QueryMMDB(arg1:string,arg2:string,arg3:string):Promise<bridge.FlagResult>;

export function Readdir(arg1:string):Promise<bridge.FlagResult>;

export function Readfile(arg1:string,arg2:bridge.IOOptions):Promise<bridge.FlagResult>;

export function RemoveScheduledTask(arg1:number):Promise<void>;

export function Removefile(arg1:string):Promise<bridge.FlagResult>;

export function Requests(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string,arg5:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function RestartApp():Promise<bridge.FlagResult>;

export function ShowMainWindow():Promise<void>;

export function StartServer(arg1:string,arg2:string,arg3:bridge.ServerOptions):Promise<bridge.FlagResult>;

export function StopServer(arg1:string):Promise<bridge.FlagResult>;

export function UnzipGZFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UnzipTarGZFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UnzipZIPFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UpdateTray(arg1:bridge.TrayContent):Promise<void>;

export function UpdateTrayMenus(arg1:Array<bridge.MenuItem>):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function ValidateCron(arg1:string):Promise<bridge.FlagResult>;

export function Writefile(arg1:string,arg2:string,arg3:bridge.IOOptions):Promise<bridge.FlagResult>;
