// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['bridge']['App']['AbsolutePath'](arg1);
}

export function AddScheduledTask(arg1, arg2) {
  return window['go']['bridge']['App']['AddScheduledTask'](arg1, arg2);
}

export function Copyfile(arg1, arg2) {
  return window['go']['bridge']['App']['Copyfile'](arg1, arg2);
}

export function Download(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['Download'](arg1, arg2, arg3, arg4, arg5);
}

export function Exec(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['Exec'](arg1, arg2, arg3);
}

export function ExecBackground(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['ExecBackground'](arg1, arg2, arg3, arg4, arg5);
}

export function ExitApp() {
  return window['go']['bridge']['App']['ExitApp']();
}

export function FileExists(arg1) {
  return window['go']['bridge']['App']['FileExists'](arg1);
}

export function GetEnv() {
  return window['go']['bridge']['App']['GetEnv']();
}

export function GetInterfaces() {
  return window['go']['bridge']['App']['GetInterfaces']();
}

export function HttpDelete(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['HttpDelete'](arg1, arg2, arg3);
}

export function HttpGet(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['HttpGet'](arg1, arg2, arg3);
}

export function HttpHead(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['HttpHead'](arg1, arg2, arg3);
}

export function HttpPatch(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['HttpPatch'](arg1, arg2, arg3, arg4);
}

export function HttpPost(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['HttpPost'](arg1, arg2, arg3, arg4);
}

export function HttpPut(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['HttpPut'](arg1, arg2, arg3, arg4);
}

export function KillProcess(arg1) {
  return window['go']['bridge']['App']['KillProcess'](arg1);
}

export function ListServer() {
  return window['go']['bridge']['App']['ListServer']();
}

export function Makedir(arg1) {
  return window['go']['bridge']['App']['Makedir'](arg1);
}

export function Movefile(arg1, arg2) {
  return window['go']['bridge']['App']['Movefile'](arg1, arg2);
}

export function Notify(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['Notify'](arg1, arg2, arg3);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['bridge']['App']['OnSecondInstanceLaunch'](arg1);
}

export function ProcessInfo(arg1) {
  return window['go']['bridge']['App']['ProcessInfo'](arg1);
}

export function Readfile(arg1) {
  return window['go']['bridge']['App']['Readfile'](arg1);
}

export function RemoveScheduledTask(arg1) {
  return window['go']['bridge']['App']['RemoveScheduledTask'](arg1);
}

export function Removefile(arg1) {
  return window['go']['bridge']['App']['Removefile'](arg1);
}

export function Requests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['Requests'](arg1, arg2, arg3, arg4, arg5);
}

export function RestartApp() {
  return window['go']['bridge']['App']['RestartApp']();
}

export function StartServer(arg1, arg2) {
  return window['go']['bridge']['App']['StartServer'](arg1, arg2);
}

export function StopServer(arg1) {
  return window['go']['bridge']['App']['StopServer'](arg1);
}

export function UnzipGZFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipGZFile'](arg1, arg2);
}

export function UnzipZIPFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipZIPFile'](arg1, arg2);
}

export function UpdateTray(arg1) {
  return window['go']['bridge']['App']['UpdateTray'](arg1);
}

export function UpdateTrayMenus(arg1) {
  return window['go']['bridge']['App']['UpdateTrayMenus'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['Upload'](arg1, arg2, arg3, arg4, arg5);
}

export function Writefile(arg1, arg2) {
  return window['go']['bridge']['App']['Writefile'](arg1, arg2);
}
