// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {options} from '../models';

export function AbsolutePath(arg1:string):Promise<bridge.FlagResult>;

export function CheckPermissions(arg1:string):Promise<bridge.FlagResult>;

export function Copyfile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function CreateSchTask(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function DeleteSchTask(arg1:string):Promise<bridge.FlagResult>;

export function Download(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Exec(arg1:string,arg2:Array<string>):Promise<bridge.FlagResult>;

export function ExecBackground(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<bridge.FlagResult>;

export function FileExists(arg1:string):Promise<bridge.FlagResult>;

export function GetEnv():Promise<bridge.EnvResult>;

export function GetInterfaces():Promise<bridge.FlagResult>;

export function GetSystemProxy():Promise<bridge.FlagResult>;

export function HttpGet(arg1:string,arg2:{[key: string]: string}):Promise<bridge.HTTPResult>;

export function KillProcess(arg1:number):Promise<bridge.FlagResult>;

export function Makedir(arg1:string):Promise<bridge.FlagResult>;

export function Movefile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ProcessInfo(arg1:number):Promise<bridge.FlagResult>;

export function QuerySchTask(arg1:string):Promise<bridge.FlagResult>;

export function Readfile(arg1:string):Promise<bridge.FlagResult>;

export function Removefile(arg1:string):Promise<bridge.FlagResult>;

export function RestartApp():Promise<bridge.FlagResult>;

export function SetSystemProxy(arg1:boolean,arg2:string):Promise<bridge.FlagResult>;

export function SwitchPermissions(arg1:boolean,arg2:string):Promise<bridge.FlagResult>;

export function UnzipGZFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UnzipZIPFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Writefile(arg1:string,arg2:string):Promise<bridge.FlagResult>;
