// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['bridge']['App']['AbsolutePath'](arg1);
}

export function CloseMMDB(arg1, arg2) {
  return window['go']['bridge']['App']['CloseMMDB'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['bridge']['App']['CopyFile'](arg1, arg2);
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bridge']['App']['Download'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Exec(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['Exec'](arg1, arg2, arg3);
}

export function ExecBackground(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['ExecBackground'](arg1, arg2, arg3, arg4, arg5);
}

export function ExitApp() {
  return window['go']['bridge']['App']['ExitApp']();
}

export function FileExists(arg1) {
  return window['go']['bridge']['App']['FileExists'](arg1);
}

export function GetEnv() {
  return window['go']['bridge']['App']['GetEnv']();
}

export function GetInterfaces() {
  return window['go']['bridge']['App']['GetInterfaces']();
}

export function IsStartup() {
  return window['go']['bridge']['App']['IsStartup']();
}

export function KillProcess(arg1, arg2) {
  return window['go']['bridge']['App']['KillProcess'](arg1, arg2);
}

export function ListServer() {
  return window['go']['bridge']['App']['ListServer']();
}

export function MakeDir(arg1) {
  return window['go']['bridge']['App']['MakeDir'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['bridge']['App']['MoveFile'](arg1, arg2);
}

export function Notify(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['Notify'](arg1, arg2, arg3, arg4);
}

export function OpenMMDB(arg1, arg2) {
  return window['go']['bridge']['App']['OpenMMDB'](arg1, arg2);
}

export function ProcessInfo(arg1) {
  return window['go']['bridge']['App']['ProcessInfo'](arg1);
}

export function QueryMMDB(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['QueryMMDB'](arg1, arg2, arg3);
}

export function ReadDir(arg1) {
  return window['go']['bridge']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['bridge']['App']['ReadFile'](arg1, arg2);
}

export function RemoveFile(arg1) {
  return window['go']['bridge']['App']['RemoveFile'](arg1);
}

export function Requests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['Requests'](arg1, arg2, arg3, arg4, arg5);
}

export function RestartApp() {
  return window['go']['bridge']['App']['RestartApp']();
}

export function ShowMainWindow() {
  return window['go']['bridge']['App']['ShowMainWindow']();
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer(arg1) {
  return window['go']['bridge']['App']['StopServer'](arg1);
}

export function UnzipGZFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipGZFile'](arg1, arg2);
}

export function UnzipTarGZFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipTarGZFile'](arg1, arg2);
}

export function UnzipZIPFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipZIPFile'](arg1, arg2);
}

export function UpdateTray(arg1) {
  return window['go']['bridge']['App']['UpdateTray'](arg1);
}

export function UpdateTrayMenus(arg1) {
  return window['go']['bridge']['App']['UpdateTrayMenus'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bridge']['App']['Upload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['WriteFile'](arg1, arg2, arg3);
}
